api_platform:
    title: 'Games API'
    description: 'APi permettant de récupérer les informations stockées à propos des différents jeux référencés sur le site.'
    version: '1.0.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [2]